version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: customerfiledb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5434:5432"